name: test

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  IDF_COMPONENT_MANAGER: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # ESP-IDF versions and targets
        idf_ver: [ v4.4, v5.0, v5.1, v5.2 ]
        idf_target: [ esp32, esp32s2, esp32s3, esp32c3, esp32h2 ]
        # Filter out unsupported combinations
        exclude:
          - { idf_target: esp32h2, idf_ver: v4.4 }
    container: espressif/idf:release-${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Component Manager
        run: |
          . ${IDF_PATH}/export.sh
          pip install --upgrade idf-component-manager

      - name: Build
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        working-directory: example
        run: |
          . ${IDF_PATH}/export.sh
          idf.py build

  platformio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install platformio
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Setup Component Manager
        run: |
          pip install --upgrade idf-component-manager

      - name: Build
        run: platformio run -d example
